### ISSUE TITLE
jsk sh pip is not working

### ISSUE THREAD

**Issue by Kigou-No1** [Gorialis/jishaku#126]
## Summary

jsk sh pip is not working

## Reproduction steps

jsk sh pip --version
jsk sh pip3 --version

If you execute either of the above two codes, `[status] Return code -9` will be displayed.
And I'm not good at English, so I use Google Translate. I'm sorry if the text is strange.

## Expected results

```
$ pip --version


pip 21.2.4 from /home/****/.local/lib/python3.8/site-packages/pip (python 3.8)
```

## Actual results

```
$ pip --version


[status] Return code -9
```

## Checklist

- [x] I have updated discord.py and jishaku to the latest available versions and have confirmed that this issue is still present
- [x] I have searched the open issues for duplicates
- [x] I have shown the entire traceback, if possible
- [x] I have removed my token from display, if visible

## System information

discord.py,pip and jishaku version.
```
- discord.py v1.7.3
- pip v21.2.4
- jishaku v2.2.0
```

Result of python3 -m discord -v
```
- Python v3.8.10-final
- discord.py v1.7.3-final
- aiohttp v3.7.3
- system info: Linux 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021
```

Result of pip show jishaku
```
Name: jishaku
Version: 2.2.0
Summary: A discord.py extension including useful tools for bot development and debugging.
Home-page: https://github.com/Gorialis/jishaku
Author: Devon (Gorialis) R
Author-email: None
License: MIT
Location: /usr/local/lib/python3.8/dist-packages
Requires: click, discord.py, braceexpand, import-expression
Required-by:
```

## Additional Information
Operation image
![スクリーンショット 2021-08-14 020658](https://user-images.githubusercontent.com/53385458/129394898-da623951-ae70-4f4d-ba4c-636eb2b03a2b.png)

**Comment by Gorialis** [comment]
pip は終了ステータスのドキュがあんまりないから、これは本当にpipの所為かシェル自体が出しているかは不明です。　jsk sh で他のコマンドが使用できるなら、これは多分環境による問題になると思う (間違ったpipを実行している・pipはpythonかsite-packagesが見つからない・などなど)

`whereis pip`, `which pip`とpip以外のコマンドを`jsk sh`で試してみてください。`jsk sh`が全く動かない場合は`bash`をインストールするかシェルのコンフィグで解決されるはずですが、pipだけならより深い調査が必要かもしれません

**Comment by kousakirai** [comment]
似たような事例で、同じかはわからないのですが、
`$ jsk git pull origin master`を実行すると
```Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/jishaku/features/shell.py", line 46, in jsk_shell
    interface = PaginatorInterface(ctx.bot, paginator, owner=ctx.author)
  File "/usr/local/lib/python3.8/site-packages/jishaku/shim/paginator_200.py", line 73, in __init__
    self.timeout = kwargs.pop('timeout', 7200)
  File "/usr/local/lib/python3.8/site-packages/discord/ui/view.py", line 247, in timeout
    if self.__timeout_task is not None:
AttributeError: 'PaginatorInterface' object has no attribute '_View__timeout_task'```
このエラーが返ってきてしまって使えません。shコマンドも同じく使えません。
環境は
```
# 使用ライブラリ
discord.py v2.0.0a Jishaku Githubから下ろしている
# OS
Ubuntu 20.04
```になってます
