### ISSUE TITLE
PaginatorInterface issue

### ISSUE THREAD

**Issue by Motzumoto** [Gorialis/jishaku#160]
## Summary

Anything that requires a paginator does not work

## Reproduction steps

use any command that requires a paginator 

## Expected results

I expect the command to work and the paginator to function

## Actual results

I get an error traceback

```py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.9/site-packages/jishaku/features/shell.py", line 46, in jsk_shell
    interface = PaginatorInterface(ctx.bot, paginator, owner=ctx.author)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/jishaku/shim/paginator_200.py", line 73, in __init__
    self.timeout = kwargs.pop('timeout', 7200)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/discord/ui/view.py", line 252, in timeout
    if self.__timeout_task is not None:
AttributeError: 'PaginatorInterface' object has no attribute '_View__timeout_task'
```

## Checklist

- [x] I have updated discord.py and jishaku to the latest available versions and have confirmed that this issue is still present
- [x] I have searched the open issues for duplicates
- [x] I have shown the entire traceback, if possible
- [x] I have removed my token from display, if visible

## System information

Name: jishaku
Version: 2.3.2a391+g046189f.master
Summary: A discord.py extension including useful tools for bot development and debugging.
Home-page: https://github.com/Gorialis/jishaku
Author: Devon (Gorialis) R
Author-email: None
License: MIT
Location: /home/ubuntu/.local/lib/python3.9/site-packages
Requires: braceexpand, import-expression, importlib-metadata, click
Required-by: 

Name: discord.py
Version: 2.0.0a4007+ga0618ef7
Summary: A Python wrapper for the Discord API
Home-page: https://github.com/Rapptz/discord.py
Author: Rapptz
Author-email: None
License: MIT
Location: /home/ubuntu/.local/lib/python3.9/site-packages
Requires: aiohttp
Required-by: wavelink, topggpy, discord-ext-menus, discord-argparse, dblpy, buttons

**Comment by Calciumcarbonate321** [comment]
I have this same issue

**Comment by Iinksafe** [comment]
Can reproduce.
![image](https://user-images.githubusercontent.com/78565096/161289463-75459c4d-245e-4099-9b6b-c758ef0a5d4a.png)
