### ISSUE TITLE
keyerror: 'locals'

### ISSUE THREAD

**Issue by sifte** [Gorialis/jishaku#161]
## Summary

Bug

## Reproduction steps
```py
print(1)
```
I `jsk py`'d the code above but it raises everytime I try to run code
## Expected results

It working

## Actual results
```py
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.10/site-packages/jishaku/features/python.py", line 149, in jsk_python
    async for send, result in AsyncSender(executor):
  File "/app/.heroku/python/lib/python3.10/site-packages/jishaku/functools.py", line 109, in _internal
    value = await base.asend(self.send_value)
  File "/app/.heroku/python/lib/python3.10/site-packages/jishaku/repl/compilation.py", line 143, in traverse
    yield await func(*self.args)
  File "<repl>", line 18, in _repl_coroutine
KeyError: 'locals' 
```

## Checklist

- [ ] I have updated discord.py and jishaku to the latest available versions and have confirmed that this issue is still present
- [ ] I have searched the open issues for duplicates
- [x] I have shown the entire traceback, if possible
- [x] I have removed my token from display, if visible

## System information

d.py: 2.0.0a4017+ge79895d
jsk: 2.3.2a395+g5acf09e.master

**Comment by Gorialis** [comment]
Your jishaku is out of date. Update it and reload and this should be fixed.
