### ISSUE TITLE
Jishaku broke on discord.py new breaking changes

### ISSUE THREAD

**Issue by timelessnesses** [Gorialis/jishaku#164]
## Summary

Discord.py changed every cog action to asynchrnous so your setup won't works at all

## Reproduction steps

Install discord.py from github  
then load cog like this
```py
await bot.load_extension('jishaku')
```

## Expected results

The jishaku loaded successfully

## Actual results

```py
C:\Users\moopi\AppData\Local\pypoetry\Cache\virtualenvs\vynx_rewrite_2.0-0j8VIO9d-py3.9\lib\site-packages\jishaku\cog.py:55: RuntimeWarning: coroutine 'BotBase.add_cog' was never awaited
  bot.add_cog(Jishaku(bot=bot))
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
TagsCog - Unloaded
---
Traceback (most recent call last):
  File "C:\Users\moopi\AppData\Local\pypoetry\Cache\virtualenvs\vynx_rewrite_2.0-0j8VIO9d-py3.9\lib\site-packages\discord\ext\commands\bot.py", line 842, in _load_from_module_spec
    await setup(self)
TypeError: object NoneType can't be used in 'await' expression

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Desktop\Vynx-Rewrite-2.0\main.py", line 139, in <module>
    asyncio.run(main(client))
  File "f:\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "f:\python\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "F:\Desktop\Vynx-Rewrite-2.0\main.py", line 131, in main
    await load_cogs(client)
  File "F:\Desktop\Vynx-Rewrite-2.0\main.py", line 111, in load_cogs
    await client.load_extension("jishaku")
  File "C:\Users\moopi\AppData\Local\pypoetry\Cache\virtualenvs\vynx_rewrite_2.0-0j8VIO9d-py3.9\lib\site-packages\discord\ext\commands\bot.py", line 908, in load_extension
    await self._load_from_module_spec(spec, name)
  File "C:\Users\moopi\AppData\Local\pypoetry\Cache\virtualenvs\vynx_rewrite_2.0-0j8VIO9d-py3.9\lib\site-packages\discord\ext\commands\bot.py", line 847, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'jishaku' raised an error: TypeError: object NoneType can't be used in 'await' expression
```

## Checklist

- [x] I have updated discord.py and jishaku to the latest available versions and have confirmed that this issue is still present
- [x] I have searched the open issues for duplicates
- [x] I have shown the entire traceback, if possible
- [x] I have removed my token from display, if visible

## System information

```py
PS F:\Desktop\Vynx-Rewrite-2.0> pip show jishaku
Name: jishaku
Version: 2.3.2
Summary: A discord.py extension including useful tools for bot development and debugging.
Home-page: https://github.com/Gorialis/jishaku
Author: Devon (Gorialis) R
Author-email:
License: MIT
Location: c:\users\moopi\appdata\local\pypoetry\cache\virtualenvs\vynx_rewrite_2.0-0j8vio9d-py3.9\lib\site-packages
Requires: braceexpand, click, import-expression
Required-by:
PS F:\Desktop\Vynx-Rewrite-2.0> pip show discord.py
Name: discord.py
Version: 2.0.0a4081+g5892bbd8
Summary: A Python wrapper for the Discord API
Home-page: https://github.com/Rapptz/discord.py
Author: Rapptz
Author-email:
License: MIT
Location: c:\users\moopi\appdata\local\pypoetry\cache\virtualenvs\vynx_rewrite_2.0-0j8vio9d-py3.9\lib\site-packages
Requires: aiohttp
Required-by: discord, discord-ext-menus, slash-util
```

**Comment by timelessnesses** [comment]
nvm there's async_setup
