### ISSUE TITLE
About the error when restarting the bot

### ISSUE THREAD

**Issue by Takkun0530** [Gorialis/jishaku#90]
I'm using a shell script to allow the bot to restart, but when I use jishaku to log out (`jsk logout`) and restart, I get the following error message:
```py
Unhandled exception during Client.run shutdown.
task: <Task finished name='Task-118' coro=<PaginatorInterface.wait_loop() done, defined at /home/takkun/.local/lib/python3.8/site-packages/jishaku/paginators.py:206> exception=RuntimeError('Session is closed')>
Traceback (most recent call last):
  File "/home/takkun/.local/lib/python3.8/site-packages/jishaku/paginators.py", line 236, in wait_loop
    payload = await self.bot.wait_for('raw_reaction_add', check=check, timeout=self.timeout)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 476, in wait_for
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/takkun/.local/lib/python3.8/site-packages/jishaku/paginators.py", line 268, in wait_loop
    await self.message.remove_reaction(emoji, self.bot.user)
  File "/home/takkun/.local/lib/python3.8/site-packages/discord/message.py", line 1186, in remove_reaction
    await self._state.http.remove_own_reaction(self.channel.id, self.id, emoji)
  File "/home/takkun/.local/lib/python3.8/site-packages/discord/http.py", line 185, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "/home/takkun/.local/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/home/takkun/.local/lib/python3.8/site-packages/aiohttp/client.py", line 381, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed
```

What does this mean?
And how can I fix it?

**[Shell script source]**
```sh
#!/bin/bash
while :
do
    python3.8 main.py
    if [ "false" = `cat reboot.txt` ]; then
        break
    fi
done
```

**[Source of main.py]**
https://gist.github.com/dpy-manager-bot/b74e2ccb741260698c6d073ba1ecf2ae#file-main-py

**Comment by Gorialis** [comment]
If your bot needs to have the lifetime of its interpreter managed, I recommend using a service manager (like systemd) instead of writing your own shell scripts, since it can prevent rapid restarts or deadlocks that might make Discord reset your bot token for abuse.

Nevertheless, the behavior you're seeing here is *technically* a bug, but it's more that aiohttp sucks, and raises `RuntimeError` out of nowhere instead of one of their documented usage exceptions - nearly any of which would have made the way to solve this a lot less ugly.

This will be fixed by v2.

**Comment by Takkun0530** [comment]
I understood. Thank you very much.

**Comment by Gorialis** [comment]
This should be fixed on master, and so will be fixed by v2.
